version: "3.3"
services:
  solr-indexer:
    build:
      context: ./digital-library-solr-indexer
      dockerfile: Dockerfile.dev
    image: digital-library/solr-indexer-dev
    container_name: digital-library-solr-indexer
    depends_on:
      - ldpath
    #  - postgres
    #  - mongo
    command:
      [
        "./scripts/wait-for-it.sh",
        "ldpath:9086",
        "--strict",
        "--timeout=60",
        "--",
        "./startDev.sh"
      ]
    links:
      - ldpath
    #  - postgres:db
    #  - mongo
    #ports:
    #  - "9229:9229"
    volumes:
      - ./digital-library-solr-indexer:/opt/app

  ldpath:
    build:
      context: ./digital-library-ldpath
      dockerfile: Dockerfile.dev
    image: digital-library/ldpath-dev
    container_name: digital-library-ldpath
    #depends_on:
    #  - redis
    #  - postgres
    #  - mongo
    #command:
    #  [
    #    "./scripts/wait-for-it.sh",
    #    "postgres:5432",
    #    "--strict",
    #    "--timeout=60",
    #    "--",
    #    "yarn",
    #    "${COMMAND}",
    #  ]
    #links:
    #  - redis
    #  - postgres:db
    #  - mongo
    ports:
      - "9086:9086"
    volumes:
      - ./digital-library-ldpath:/opt/app

