version: "3.3"
services:
  solr:
    image: solr:8.8
    container_name: digital-library-solr
    ports:
      - "8983:8983"
    volumes:
      - ~/volumes/development/solr:/var/solr

  fedora-repository:
    image: tomcat:8.5.64-jdk8-openjdk-slim-buster
    volumes:
      - ./resources/fcrepo.war:/usr/local/tomcat/webapps/fcrepo.war
    ports:
      - '8080:8080'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb1
      MYSQL_USER: testuser
      MYSQL_PASSWORD: root

  solr-indexer:
    build:
      context: ./digital-library-solr-indexer
      dockerfile: Dockerfile.dev
    image: digital-library/solr-indexer-dev
    container_name: digital-library-solr-indexer
    depends_on:
      - ldpath
      - solr
    #  - mongo
    command:
      [
        "./scripts/wait-for-it.sh",
        "ldpath:9086",
        "--strict",
        "--timeout=60",
        "--",
        "./startDev.sh"
      ]
    links:
      - ldpath
      - solr
    #  - mongo
    volumes:
      - ./digital-library-solr-indexer:/opt/app

  ldpath:
    build:
      context: ./digital-library-ldpath
      dockerfile: Dockerfile.dev
    image: digital-library/ldpath-dev
    container_name: digital-library-ldpath
    depends_on:
      - ldpath-program
    command:
      [
        "./scripts/wait-for-it.sh",
        "ldpath-program:8181",
        "--strict",
        "--timeout=60",
        "--",
        "./startDev.sh"
      ]
    links:
      - ldpath-program
    ports:
      - "9086:9086"
    volumes:
      - ./digital-library-ldpath:/opt/app

  ldpath-program:
    build:
      context: ./digital-library-ldpath-program
      dockerfile: Dockerfile.dev
    image: digital-library/ldpath-program-dev
    container_name: digital-library-ldpath-program
    ports:
      - "8181:8181"
    volumes:
      - ./digital-library-ldpath-program/src:/opt/app/src
      
