version: "3.3"
services:
  solr:
    image: solr:8.8
    container_name: digital-library-solr
    ports:
      - "8983:8983"
    volumes:
      - ~/volumes/development/solr:/var/solr

  fedora-repository:
    build:
      context: ./resources/tomcat
      dockerfile: Dockerfile
    image: digital-library/fedora-repository
    container_name: digital-library-fedora-repository
    command: [
      "catalina.sh",
      "run"
    ]
    volumes:
      - ~/volumes/development/fedora:/usr/local/tomcat/oa-discovery-data
    ports:
      - '8080:8080'
      - '61616:61616'

  solr-indexer:
    build:
      context: ./digital-library-solr-indexer
      dockerfile: Dockerfile.dev
    image: digital-library/solr-indexer-dev
    container_name: digital-library-solr-indexer
    depends_on:
      - ldpath
      - solr
      - fedora-repository
    command:
      [
        "./scripts/wait-for-it.sh",
        "ldpath:9086",
        "--strict",
        "--timeout=60",
        "--",
        "./scripts/wait-for-it.sh",
        "fedora-repository:61616",
        "--strict",
        "--timeout=60",
        "--",
        "./startDev.sh"
      ]
    links:
      - ldpath
      - solr
      - fedora-repository
    volumes:
      - ./digital-library-solr-indexer:/opt/app

  ldpath:
    build:
      context: ./digital-library-ldpath
      dockerfile: Dockerfile.dev
    image: digital-library/ldpath-dev
    container_name: digital-library-ldpath
    depends_on:
      - ldpath-program
    command:
      [
        "./scripts/wait-for-it.sh",
        "ldpath-program:8181",
        "--strict",
        "--timeout=60",
        "--",
        "./startDev.sh"
      ]
    links:
      - ldpath-program
    ports:
      - "9086:9086"
    volumes:
      - ./digital-library-ldpath:/opt/app

  ldpath-program:
    build:
      context: ./digital-library-ldpath-program
      dockerfile: Dockerfile.dev
    image: digital-library/ldpath-program-dev
    container_name: digital-library-ldpath-program
    ports:
      - "8181:8181"
    volumes:
      - ./digital-library-ldpath-program/src:/opt/app/src
      
